classDiagram
class Notifier {
  <<interface>>
  +notifyResult(message: String)
}

class BinaryOperation {
  +BinaryOperation(notifier: Notifier)
  +execute(a: double, b: double) void
  +validate(a: double, b: double) boolean
  +onValidationError(a: double, b: double) void
  +formatMessage(a: double, b: double, result: double) String
  +compute(a: double, b: double) double*
  +getSymbol() String*
}

class SumOperation {
  +SumOperation(notifier: Notifier)
  +compute(a: double, b: double) double
  +getSymbol() String
}

class DivideOperation {
  +DivideOperation(notifier: Notifier)
  +validate(a: double, b: double) boolean
  +onValidationError(a: double, b: double) void
  +compute(a: double, b: double) double
  +getSymbol() String
}

class MainStep3 {
  +main(args: String[])
}

Notifier <|-- ConsoleNotifier
Notifier <|-- FileNotifier
BinaryOperation <|-- SumOperation
BinaryOperation <|-- DivideOperation
MainStep3 --> BinaryOperation : mappa
BinaryOperation --> Notifier
